import {
  ACCESS_OPERATIONS,
  POLICY_COMMENT_PREFIX,
  literal,
  policyName,
  quote,
  type AccessRule,
  type CompiledPolicy,
  type CompiledTable,
  type TableAccess,
} from "./access.ts";

export function policyStatement(policy: CompiledPolicy): string {
  const target = `${quote(policy.name)} ON ${quote(policy.table)} FOR ${policy.operation.toUpperCase()}`;
  const check =
    policy.operation === "insert"
      ? `WITH CHECK (${policy.expression})`
      : policy.operation === "update"
        ? `USING (${policy.expression}) WITH CHECK (${policy.expression})`
        : `USING (${policy.expression})`;
  return [
    `CREATE POLICY ${target}\n  ${check};`,
    `COMMENT ON POLICY ${quote(policy.name)} ON ${quote(policy.table)} IS ${literal(`${POLICY_COMMENT_PREFIX}${policy.hash}`)};`,
  ].join("\n");
}

/**
 * Renders the idempotent migration for the declared access state. Tables that
 * were previously declared but no longer are keep RLS enabled and lose their
 * policies, so they fall back to Deny.
 */
export function renderAccessMigration(
  tables: readonly CompiledTable[],
  removedTables: readonly string[],
): string {
  const sections = [
    "-- Generated by @chromatis/base from access.toml. Edit access.toml, then regenerate.",
  ];
  for (const table of removedTables) {
    sections.push(
      [
        `-- ${table}: no longer declared; RLS stays enabled so access is denied`,
        `ALTER TABLE ${quote(table)} ENABLE ROW LEVEL SECURITY;`,
        ...ACCESS_OPERATIONS.map(
          (operation) =>
            `DROP POLICY IF EXISTS ${quote(policyName(table, operation))} ON ${quote(table)};`,
        ),
      ].join("\n"),
    );
  }
  for (const entry of tables) {
    sections.push(
      [
        `-- ${entry.table}`,
        `ALTER TABLE ${quote(entry.table)} ENABLE ROW LEVEL SECURITY;`,
        `ALTER TABLE ${quote(entry.table)} ${entry.force ? "FORCE" : "NO FORCE"} ROW LEVEL SECURITY;`,
        ...ACCESS_OPERATIONS.map(
          (operation) =>
            `DROP POLICY IF EXISTS ${quote(policyName(entry.table, operation))} ON ${quote(entry.table)};`,
        ),
        ...entry.policies.map(policyStatement),
      ].join("\n"),
    );
  }
  return `${sections.join("\n\n")}\n`;
}

function describeRule(rule: AccessRule): string {
  if (rule.public) {
    return "PUBLIC (no login required)";
  }
  const parts: string[] = [];
  if (rule.role) {
    parts.push(rule.role);
  }
  if (rule.userColumn) {
    parts.push(`owner via ${rule.userColumn}`);
  }
  if (rule.through) {
    parts.push(`through ${rule.through}`);
  }
  return parts.join(" AND ");
}

/** Human-readable access overview for one table. */
export function describeTableAccess(entry: TableAccess): string {
  const lines = [entry.table + (entry.force ? " (FORCE RLS)" : "")];
  for (const operation of ACCESS_OPERATIONS) {
    const rules = entry.rules[operation];
    lines.push(
      "",
      `  ${operation.toUpperCase()}`,
      rules.length === 0
        ? "    DENY (no rule)"
        : `    ${rules.map(describeRule).join("\n    OR ")}`,
    );
  }
  return lines.join("\n");
}
